name: Deploy to EC2

on:
  push:
    branches:
      - main  # Cambia "main" si tu rama principal tiene otro nombre

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}                  # IP pública o DNS de tu instancia EC2
        username: ${{ secrets.EC2_USER }}          # Usuario de tu servidor EC2 (generalmente "ubuntu" o "ec2-user")
        key: ${{ secrets.EC2_SSH_KEY }}            # Clave SSH privada configurada como secreto en GitHub
        script: |
          cd /var/www/helloworld                  # Ruta de tu proyecto
          git pull origin main                    # Obtén los últimos cambios
          npm install                             # Instala las dependencias
