name: Deploy to EC2

on:
  push:
    branches:
      - main  # Cambia "main" si tu rama principal tiene otro nombre

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        echo "Conectándose a la instancia de EC2..."
        ssh -o StrictHostKeyChecking=no ubuntu@44.203.127.237 << 'EOF'
          echo "Actualizando el servidor..."
          pkill node || true  # Detiene cualquier proceso Node.js si está corriendo
          cd ~/aws-action   # Asegúrate de que este sea el directorio correcto de tu proyecto
          git pull origin main  # Descarga los últimos cambios de tu repositorio
          npm install  # Instala dependencias
          nohup node server.js > output.log 2>&1 &  # Inicia la aplicación en segundo plano
          echo "Servidor reiniciado correctamente."
        EOF
