name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.HOST_DNS }}
        REMOTE_USER: ${{ secrets.EC2_USER }}
        TARGET: ${{ secrets.TARGET_DIR }}

    - name: Executing remote SSH commands using SSH key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "Configurando permisos..."
          sudo chown -R $USER:$USER /var/www/helloworld
          sudo chmod -R 775 /var/www/helloworld

          echo "Configurando git..."
          git config --global --add safe.directory /var/www/helloworld

          echo "Actualizando el código..."
          cd /var/www/helloworld
          git pull origin main

          echo "Instalando dependencias..."
          npm install

          echo "Instalando PM2 si es necesario..."
          sudo npm install -g pm2 || echo "PM2 ya está instalado"

          echo "Reiniciando la aplicación con PM2..."
          pm2 delete helloworld || echo "No existing process found"
          pm2 start npm --name "helloworld" -- run start  # Cambia "start" si tienes otro script
          pm2 save

          echo "Despliegue completado con éxito."
